### ISSUE TITLE
Review Proposal

### ISSUE THREAD

**Issue by mishasaggi** [GuardiansOfEarthV2/ClimateChangeLivabilityVisualizer#11]

**Comment by SahejBhatia** [comment]
[Uploading... Climate Change Livability Visualizer.docx]

**Comment by SahejBhatia** [comment]
[https://app.zenhub.com/files/305528369/ae49e4db-326b-4005-be4c-2f8efac917fb/download](https://app.zenhub.com/files/305528369/ae49e4db-326b-4005-be4c-2f8efac917fb/download)
