### ISSUE TITLE
Wireframing for the webapp

### ISSUE THREAD

**Issue by mishasaggi** [GuardiansOfEarthV2/ClimateChangeLivabilityVisualizer#12]

**Comment by SahejBhatia** [comment]
![wireframe1.jpg](https://images.zenhubusercontent.com/5f8e1522717387b777ed6472/1cc30e91-16b0-4396-af52-35f59c1962bf)![wireframe2.jpg](https://images.zenhubusercontent.com/5f8e1522717387b777ed6472/76b00c8f-2f76-4698-8b35-e82c46df0c9b)
